runtime: perl516

install_author_deps: |
    cpanm --notest -L local Dist::Zilla
    exec dzil authordeps | cpanm --notest -L local

build: |
    exec dzil listdeps | cpanm --notest -L local

test: |
    exec dzil test

release_test: |
    RELEASE_TESTING=1 exec dzil test

prove: |
    exec dzil run prove ${ROCK_ARGV}

dzil: |
    exec dzil ${ROCK_ARGV}
